![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [8]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full((7), 53.141)

array([53.141, 53.141, 53.141, 53.141, 53.141, 53.141, 53.141])

In [6]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
np.ones((5, 5)).astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [10]:
x = np.random.randn(3, 3, 3)
x

array([[[ 0.71565236, -1.82125348, -0.53661278],
        [-1.05778842,  1.05770128, -1.15305773],
        [-2.34989333, -0.33710645, -1.19150943]],

       [[-0.10468328, -1.51261189, -0.87692343],
        [-0.93270906,  0.84472435,  2.11454781],
        [-0.71139423,  1.6953084 ,  0.47434257]],

       [[-0.15972562, -0.51191241, -0.27423618],
        [ 1.04164477, -0.32565802, -0.88389166],
        [ 0.22814415, -0.298801  ,  0.76846303]]])

In [11]:
x.reshape(27,)

array([ 0.71565236, -1.82125348, -0.53661278, -1.05778842,  1.05770128,
       -1.15305773, -2.34989333, -0.33710645, -1.19150943, -0.10468328,
       -1.51261189, -0.87692343, -0.93270906,  0.84472435,  2.11454781,
       -0.71139423,  1.6953084 ,  0.47434257, -0.15972562, -0.51191241,
       -0.27423618,  1.04164477, -0.32565802, -0.88389166,  0.22814415,
       -0.298801  ,  0.76846303])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [12]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [14]:
a = np.arange(1, 26).reshape(5, -1)
print(a)
a[3,4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


20

```python
20
```

In [15]:
a[1:, 3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [16]:
a[1]

array([ 6,  7,  8,  9, 10])

```python
array([ 6,  7,  8,  9, 10])
```

In [18]:
a[2:4,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [19]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

```python
array([[ 8,  9],
       [13, 14]])
```

### 6.

Calculate the sum of all the numbers in `a`.

In [20]:
a.sum()

325

### 7.

Calculate the sum of each row in `a`.

In [26]:
for i in range(5):
    sum = a[i].sum()
    print(sum)

15
40
65
90
115


### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [27]:
a.mean() < a

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### 9.

Find the location of the minimum value in the following array `b`:

In [29]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [32]:
b.argmin()

6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [34]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [35]:
c.argmax()

5

<hr>
<hr>
<hr>